### ISSUE TITLE
Improve Template Maintainability

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#105]
**Is your feature request related to a problem? Please describe.**

Right now, the template bricks are not setup as individual dart/flutter projects which makes analysis and dependency maintenance challenging.

**Describe the solution you'd like**

- [ ] Spike [brickhub](https://brickhub.dev) for the package samples
- [x] Remodel demos and template bricks to be maintainable dart projects (i.e. move dependencies and other config from template.yaml to a pubspec.yaml) [Waiting to see what happens to mason for this one] #148 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ksanty** [comment]
@XavierChanth should we move up to high priority for work on PR43?

**Comment by xavierchanth** [comment]
This can be bumped to a low.

**Comment by xavierchanth** [comment]
Closing this issue until mason and brickhub are stable, no work can be done until then.
