### ISSUE TITLE
Shorthand namespace -n doesn't work

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_app_cli#144]
# **Describe the bug**
Shorthand namespace `-n` doesn't work (but `--namespace` does)
![image](https://user-images.githubusercontent.com/79019866/173463082-52b8fc99-5f25-4d0e-aeb6-6253d3ed68b0.png)

# **To Reproduce**
1. Get the `at_app` CLI
2. Run `at_app create at_onboarding_demo -n=@beaverarmadillo` => doesn't work
3. Run `at_app create at_onboarding_demo --namespace=@beaverarmadillo` => works

**Expected behavior**
![image](https://user-images.githubusercontent.com/79019866/173463273-4c23f078-3128-4adf-8011-91306a7e4f37.png)

**Comment by xavierchanth** [comment]
@JeremyTubongbanua shorthand is with a space, like: `-n @beaverarmadillo`
See [args](https://pub.dev/packages/args#specifying-options) on pub.dev
