### ISSUE TITLE
Malformed Sarif file upload

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#232]
### Describe the bug

The sarif file is uploaded with the additional `got codeowners file at .github/CODEOWNERS` in the head of the file.

This causes the json parsing to fail with message: `Unexpected token g in JSON at position 0`

### Steps to reproduce

Run this workflow with a `CODEOWNERS` file in the `.github` folder.

### Expected behavior

The workflow runs without fail, and uploads the sarif file without the additional line in the head.

**Comment by cpswan** [comment]
This will be fixed by V2.1.2 of the scorecard action when Dependabot comes along with a PR for it in the next day or so
