### ISSUE TITLE
Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_app_cli#24]
**Describe the solution you'd like**

Per the guidance from [dart-lang/lints](https://github.com/dart-lang/lints#migrating-from-packagepedantic):

in `pubspec.yaml`:

```diff
-  pedantic: ^1.11.0
+  lints: ^1.0.1
```

and in each `analysis_options.yaml`:

```diff
-include: package:pedantic/analysis_options.yaml
+include: package:lints/recommended.yaml
```

**Comment by TylerTrott** [comment]
Hey @XavierChanth, just going through our repos and found that you're using the pedantic dependency. Will this be code breaking while migrating to lints?

**Comment by xavierchanth** [comment]
> Hey @XavierChanth, just going through our repos and found that you're using the pedantic dependency. Will this be code breaking while migrating to lints?

I don't think there should be an issue, the linter may ask for some additional formatting/changes though.

**Comment by prasadsunny1** [comment]
How to work on this one? I see pubspec has the pedantic package, will replacing the package with lints work? I guess, nope.

**Comment by cpswan** [comment]
@prasadsunny1 see https://github.com/atsign-foundation/at_widgets/pull/232/files for an example of a similar replacement

@XavierChanth I'm assuming you want flutter_lints rather than just Dart lints

**Comment by prasadsunny1** [comment]
Understood, PR coming this way soon

**Comment by xavierchanth** [comment]
> @prasadsunny1 see https://github.com/atsign-foundation/at_widgets/pull/232/files for an example of a similar replacement
> 
> @XavierChanth I'm assuming you want flutter_lints rather than just Dart lints

Sorry, was out on holiday.
I think package:lints is fine here, no flutter code in the project.

**Comment by prasadsunny1** [comment]
All right, I'll create a fresh PR

**Comment by xavierchanth** [comment]
> All right, I'll create a fresh PR

No need, continue pushing your changes and they will be added to this PR.

**Comment by prasadsunny1** [comment]
Added `flutter_lints` as linter.
Applied few changes as per the info given by the analyzer

**Comment by prasadsunny1** [comment]
file_manager.dart has a print statement in the catch statement. I have tried to replace it with logger.
Do you think passing logger to FileManager using constructor is a good idea and all the caller for it should be updated?

**Comment by prasadsunny1** [comment]
CreateBase class has the property `name` which seems to be an override from the base class.
CreateCommand class has the property `description` which seems to be an override from the base class.

**Comment by prasadsunny1** [comment]
android_manage.dart, line: 17 
The analyzer is saying that `for each should be converted to simple `for loop`

**Comment by prasadsunny1** [comment]
Please tell me if it is all right to do these changes

**Comment by prasadsunny1** [comment]
Check the PR to understand the changes
