### ISSUE TITLE
Logout/ Switch Atsign option in boilerplate code

### ISSUE THREAD

**Issue by HamdaanAliQuatil** [atsign-foundation/at_app_cli#278]
### Is your feature request related to a problem? Please describe.

Currently, when an at_app is created, the user is provided with the option to onboard using an Atsign. However, once the user is on the home screen, there is no option to log out or switch Atsigns. This presents a usability issue as users may want to switch accounts or log out of the application for various reasons.

Adding logout in the boilerplate code will serve two purposes:

1.  Adding logout functionality to the boilerplate code simplifies the development process for building quick at_apps, allowing developers to focus on their core business logic while ensuring a complete user experience. By including the option to switch Atsigns and log out within the boilerplate, developers can expedite the creation of their applications without the need to spend extensive time researching and implementing these essential user features. 
2.  Gives the developer a boilerplate to implement logout/ switch user, which they can easily modify/customize as per their requirement.

By providing a logout functionality in the boilerplate code, developers can streamline the implementation process for such critical user features, saving time and effort.

### Describe the solution you'd like

NA

**Comment by xavierchanth** [comment]
When I created the original app template, I had the question "what is the bare minimum for an at_client powered application?" in mind.
Rather than modifying the original template, we could add another template which includes this additional functionality.
