### ISSUE TITLE
Test and Release v5.0.0

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#293]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

N/A

**Comment by xavierchanth** [comment]
@Xlin123 Would you be willing to help me with this?

**Comment by Xlin123** [comment]
> @Xlin123 Would you be willing to help me with this?

Yessir.

**Comment by Xlin123** [comment]
All packages have been published to pub.dev.

**Comment by xavierchanth** [comment]
Thank you!
