### ISSUE TITLE
Replace at_app with a simple app template / gist

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#340]
The original purpose for building at_app was to help automatically maintain several (~10-20) app templates for the atsign-foundation. But now we only need one, and the additional maintenance costs associated with at_app are no longer worth it.

We should archive at_app, and replace it with an app template repo, or a gist which contains:
- README.md (with setup instructions)
- main.dart
- pubspec.yaml
- and maybe some additional homescreen / onboarding dart files

**Comment by sachins-geekyants** [comment]
Moving to next sprint.

**Comment by xavierchanth** [comment]
app template has been completed, we need to find a place for it to live, probably the docs site.

**Comment by Sardar1208** [comment]
assigning 0SP and moving to next sprint

**Comment by sachins-geekyants** [comment]
@XavierChanth can we close this ticket ?
