### ISSUE TITLE
Add the snackbar demo app to at_app.

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#44]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Be able to generate the demo app using `at_app create -d snackbar <path>`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by cconstab** [comment]
@XavierChanth I am doing this and whilst doing it providing you some user testing for docs and code ....

this is actually two apps

the snackbar sender (to the flutter web applet

The snackbar e2e encrypted @sign to @sign app

**Comment by cconstab** [comment]
completed and pushed to trunk
