### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_app_cli#5]
**Is your feature request related to a problem? Please describe.**
Confusion between this project (at_app_cli) and at_cli

**Describe the solution you'd like**
I'd like to rename the repository to at_app based on our previous discussions, and I am seeking approval to do so.
The only other place to rename the repository is in the readme.md file's title.

**Describe alternatives you've considered**
Other names, at_skeleton, at_builder.

**Additional context**
I prefer the name at_app for the project, since it is more generic, it will make more sense long term if other commands are added to the project.

**Comment by cpswan** [comment]
LGTM - I see that CONTRIBUTING.md is ready.
