### ISSUE TITLE
Api key generator for developer instead of getting by mail.

### ISSUE THREAD

**Issue by Intiserahmed** [atsign-foundation/at_app_cli#73]
I was thinking of how fast a newbie can start developing for at_platform. So for now dev can not do production development right away with at_app which holds them to onboard with their free atsign and test their at_platform based codes. To get an api key takes time as it is done by mail. So I was thinking of API key generator would be great to reduce the time of getting api key.

Maybe we can discuss it in architecture call.

**Comment by athandle** [comment]
@Intiserahmed by default key is in package. It should not hold anyone to start.

**Comment by xavierchanth** [comment]
Closing this, APKAM should solve this issue before we get a significant number of requests for api keys.
