### ISSUE TITLE
Way to use the at_app template in an existing app

### ISSUE THREAD

**Issue by Intiserahmed** [atsign-foundation/at_app_cli#80]
**Is your feature request related to a problem? Please describe.**
If there is an existing app that wants to use at_app template they have to start rewriting from the scratch. That will take lots of time and patience.

**Describe the solution you'd like**
At_app will have a command for existing app that doesn't use at_platform. With that command they will create a new file and all the configuration file. It should be different from flutter create as it will only create the configuration file and onboarding.

**Describe alternatives you've considered**

**Additional context**
Useful for quickly switch from non-atplatform app to platform app.

**Comment by xavierchanth** [comment]
Somewhat related to #48

**Comment by xavierchanth** [comment]
We can spike this and come up with a proposal, but I suspect that the end result will not be as clean as using the original template. 

The main issue here is that we don't want to ruin the user's existing code on the off-chance that they aren't using source control. Maybe the solution here is to backup before executing, and include a restore command.

Another thing to check for is that the file to be modified is valid, so running dart analyze before modifying any files, and failing the command if dart analyze reports any issues. (Probably only for warnings/errors, info should be fine to continue)

Then how do we:

- Verify that they have the correct dependencies
- Verify that existing dependencies are compatible
- Inject the onboarding code into the project
  - Do we inject an onboarding button widget that they can use 
  or do we try to inject the onboarding widget as the first screen
  - Then if we inject as the first screen, we need to handle named vs page routes
- Make sure the platform config is up to date
  - Do we need to export minimum app requirements from each @platform package?
  - Do we need to create a new package that serves as a spec for what needs to be included in these minimum app requirements?

**Comment by Intiserahmed** [comment]
We won't ruin their existing code. It's more like creating two files(Onboarding widget file and .env file)  inside the lib folder & the platform dependencies will be added. In the lib folder we will provide a file called maybe 'plaformClient' which will contain onboarding widget. we will give the user flexibility to choose any page as their second screen. That's it.

You can look into an example of these kind of file generation by CLI [here](https://pub.dev/packages/get_cli)
